FROM golang:1.22-alpine AS builder
WORKDIR /app
ENV CGO_ENABLED=0
ENV GOFLAGS=-mod=mod
COPY go.mod go.sum ./
RUN go mod download
COPY cmd ./cmd
COPY internal ./internal
RUN go build -o /app/server ./cmd/server

FROM alpine:3.20
WORKDIR /app
RUN adduser -D app
COPY --from=builder /app/server /app/server
USER app
EXPOSE 8080
ENTRYPOINT ["/app/server"]
